# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DMWmA600PEvDDBvbjMlXlW0Vy-oXzEUT
"""

import pandas as pd
import plotly.express as px
import streamlit as st

# Leer los datos
car_data = pd.read_csv('vehicles_us.csv')

# Encabezado
st.header('Análisis interactivo de anuncios de coches 🚗')

# Botón para histograma
hist_button = st.button('Construir histograma')

if hist_button:
    st.write('Histograma de kilometraje (odometer)')
    fig = px.histogram(car_data, x="odometer")
    st.plotly_chart(fig, use_container_width=True)

# Botón para scatter
scatter_button = st.button('Construir gráfico de dispersión')

if scatter_button:
    st.write('Relación entre kilometraje y precio')
    fig = px.scatter(car_data, x="odometer", y="price")
    st.plotly_chart(fig, use_container_width=True)